### ISSUE TITLE
the demos run too slow

### ISSUE THREAD

**Issue by ShaYito** [janbender/PositionBasedDynamics#110]
I am using windows 10, vs 2019 with RTX 3060, i7-11800H, and 24G memory.
I ran the demo "DeformableCollisionDemo" and it takes about 30 seconds for the object to first fall on the torus. It seems too slow.
And I notice the demo only uses GPU when the scene appears and after that GPU is not utilized. (and the CPU was 100% taken up)
Other demos are running too slow as well.
Is this normal?

**Comment by janbender** [comment]
No. This even runs fast on my slow laptop. Did you compile in Release mode?
