### ISSUE TITLE
what parameters should be changed to simulate 2D position based fluid?

### ISSUE THREAD

**Issue by zhengxiuyu** [janbender/PositionBasedDynamics#12]
I want to use the Position based Fluids library to simulation 2D Fluids, I change the kernel to 40 / (7 * pi * h * h), but the fluids just move along the gravity. what else should I change?

**Comment by janbender** [comment]
It is correct that only the kernel has to be changed in the computation. However, maybe there is a bug in your implementation. Our library uses 3D coordinates. Did you change them to 2D? Did you also modify the mass computation? Did you check that the integral over your kernel is 1?

**Comment by zhengxiuyu** [comment]
Thanks for your answer, I have achieve 2D PBF. To simulation 2D Fluids, we need to change the 2D cubic kernel to make its integral in the support radius is 1. hence we change the m_k =  40.0f / (7.0f * pi * h2), m_l = 240.0f / (7.0f * pi * h2). what's more, we should the particle mass = density * m_radius * m_radius. In 2D, the particle represent a square not a cubic. Last but not least, if we let the fluids in x-y plane, we need not all the front an back wall.
