### ISSUE TITLE
I implemented the cloth simulation by the triangle constraint, but why the vertices of cloth oscillate highly?

### ISSUE THREAD

**Issue by tangpengbin** [janbender/PositionBasedDynamics#13]
I implemented the triangle constraint refer to your code and your paper of ContinuousMaterials, but the vertices of cloth oscillate highly.
the simulation loop is:
void positionBasedDynamics::solve()
{
	triangleModel_semiImplicitEuler();
	for (int i=0;i<maxItor;i++)                       //maxItor=5
	{
		FEMTriangleConstraint_solver();
		triangleModel_applyDelta();
	}
	triangleModel_velocityUpdate();
}
I have directly assigned the one triangle's vertices, area and invRestMat to your project at one simulation step and the calculated delta correction is the same.
Is here any other detail I have missed?
thx!

**Comment by janbender** [comment]
Did you use the area of the rest state?
Why didn't you just use our code?

**Comment by tangpengbin** [comment]
Thanks for your attention!
I want to implement your FEM triangle constraint by cuda, and intergrate it into my framework. So I need to rewrite it for my framework.
Following this figure is my cuda FEM triangle solved result:
![cuda](https://cloud.githubusercontent.com/assets/12883995/12372886/baca496e-bca1-11e5-9528-4b7382b6d8a0.png)
And I use these previous output data assigned to your work, the result is the same.
![yours](https://cloud.githubusercontent.com/assets/12883995/12372917/8a417b0e-bca2-11e5-90d0-ff14abdd52da.png)
So I really don't kown what wrong with my code.
Thank you!

**Comment by janbender** [comment]
If you get the same results, the constraint should work. Maybe you have a bug in the integration code.

**Comment by tangpengbin** [comment]
In your PDB code, you are serially solved the constraint and corrected the position one by one. 
I think is there will be trouble with the parallel correction of the particle postion after solved the constraint?
Thank you!

**Comment by janbender** [comment]
If you use a parallel correction, you will get a Jacobi solver instead of a Gauss-Seidel solver. In this case you get multiple position corrections for each particle (= number of adjacent triangles). You should use a kind of interpolation for these corrections (per vertex), e.g. sum up the corrections for each vertex and divide by the number of position corrections for this vertex.

**Comment by janbender** [comment]
There are also some papers which use the parallel Jacobi. Maybe you could have a look for that.

**Comment by tangpengbin** [comment]
Oh! I know.....
Thank you very much ! :)
