### ISSUE TITLE
how to solve the fluid particles pass through the boundary particles

### ISSUE THREAD

**Issue by zhengxiuyu** [janbender/PositionBasedDynamics#14]
I want to achieve the blue noise sampling with PBF, my intention is not to do simulation. When I locate the initial fluids particles randomly, the density difference are too much, therefore the particle can pass through the boundary. However, when I use the boundary level set to clamp the particle in the fluids region, the system can not work, just like the vedio they can not converge. 

so, in the situation, what should I do to handle the error boundary control?

**Comment by janbender** [comment]
I do not really understand your problem. Of course when you position the particles randomly you will have several loactions with a high pressure and thus large velocities. To handle large velocities correctly you must limit the time step size, sometimes you must take significantly smaller values than the ones proposed by the CFL condition. You can also use damping to make it a bit better. But why don't you just start with a pressure-free state?

**Comment by zhengxiuyu** [comment]
I remove the gravity in the simulation system, if I position the particles uniformly, all the particles are in a pressure-free state therefore they are almost not move, Finally the particles are stilling in a regular distribution. I take the fluid particles as the blue noise sampling points. If the sampling points are too regular, they are not a good blue noise sampling, this is the reason why I want to position the particles randonmly. I just hope the particles can randomly move as large as possible to achieve the pressure-free state. However, when I position the particles randomly, the system is not stable.

**Comment by janbender** [comment]
You could try to use a regular distribution of the particles at the beginning of the simulation in order to avoid high pressure forces and then apply some random forces to the particles to let them move.

**Comment by tangpengbin** [comment]
In your PDB code, you are serially solved the constraint and corrected the position one by one. 
I think is there will be trouble with the parallel correction of the particle postion after solved the constraint?
Thank you!
