### ISSUE TITLE
Some projects (e.g. RigidBodyClothCouplingDemo, ChainDemo) throw exception under VS2015 Release Win32

### ISSUE THREAD

**Issue by stanleytangerror** [janbender/PositionBasedDynamics#17]
Hi, everyone:

I built the whole solution under **VS2015 Release Win32** configurations. A few demo projects such as RigidBodyClothCouplingDemo and ChainDemo throw exception when running.

A few warnings were thrown when building.
```
>..\..\..\Demos\CouplingDemos\RigidBodyClothCouplingDemo.cpp(451): warning C4316: 'PBD::RigidBody': object allocated on the heap may not be aligned 16
```
 
I debugged these two projects, both threw exceptions at around line 79 of RigidBody.h, where

```
void initialBody(...)
{
    // ...
    m_x = x; 
    m_x0 = x;
    m_lastX = x;
    m_oldX = x;
    m_v.setZero();
    m_a.setZero();
    m_q = rotation; // throw exception
    m_q0 = rotation;
    m_lastQ = rotation;
    m_oldQ = rotation;
    // ...
}
```

I changed the default alignment of the project to 16 (not worked for me), then modified RigidBodyClothCouplingDemo.cpp around line 410 from 
```
rb[0] = new RigidBody();
rb[0]->initBody(0.0f,
	Eigen::Vector3f(-5.0, 0.0f, -5.0),
	computeInertiaTensorBox(1.0f, 0.5f, 0.5f, 0.5f),
	Eigen::Quaternionf(1.0f, 0.0f, 0.0f, 0.0f), 
	vd, mesh);
``` 
to
```
RigidBody* p = (RigidBody*) _aligned_malloc(sizeof RigidBody, 16);
rb[0] = new (p) RigidBody();
rb[0]->initBody(0.0f,
	Eigen::Vector3f(-5.0, 0.0f, -5.0),
	computeInertiaTensorBox(1.0f, 0.5f, 0.5f, 0.5f),
	Eigen::Quaternionf(1.0f, 0.0f, 0.0f, 0.0f), 
	vd, mesh);
std::cout << "0 " << rb[0]->getMass() << std::endl;
```
which made the project run temporarily (It was a bad modification, which I still got exceptions when exit or change some twkBar options).

I am wondering this issue comes from the Win32's alignment. I got stuck here, did I do something wrong in the whole procedure?

Thanks a lot.

Stanley

**Comment by janbender** [comment]
Hi,

the simple solution for thus problem is to build the project with the x64 configuration. 
I think I also know the solution for the Win32 problem. I will try to fix it later.

Jan

**Comment by janbender** [comment]
Hi, 

I tried to fix it. However, this is too much effort for this special problem. It only occurs when you use an x86 configuration on an x64 platform. If you are interested to fix it, take a look at: 

https://eigen.tuxfamily.org/dox/group__DenseMatrixManipulation__Alignement.html

Jan
