### ISSUE TITLE
Compilation error C2664 in MiniGL.cpp

### ISSUE THREAD

**Issue by mmmovania** [janbender/PositionBasedDynamics#4]
I get the following compilation error in MiniGL.cpp on line 421 in VisualStudio2012 on Windows 8.1 64-bit machine
`1>..\..\..\Demos\Visualization\MiniGL.cpp(422): error C2664: 'int TwGLUTModifiersFunc(int (__cdecl *)(void))' : cannot convert argument 1 from 'int (__stdcall *)(void)' to 'int (__cdecl *)(void)'
1>          None of the functions with this name in scope match the target type`

Solution:
Change the line to following
`typedef int (TW_GLUT_CALL *GLUTgetmodifiersfun)(void);
TwGLUTModifiersFunc((GLUTgetmodifiersfun)glutGetModifiers);`

Are these changes correct?

**Comment by janbender** [comment]
Can you try to rebuild the project for x64?

**Comment by mmmovania** [comment]
OK I will and revert asap. By the way the defualt glew and freeglut project linker->command line->additional options contains /MACHINE:X86 you need to remove this setting for x64 build.
