### ISSUE TITLE
ClothDemo runtime Debug assertion in Debug build and crash in Release build

### ISSUE THREAD

**Issue by mmmovania** [janbender/PositionBasedDynamics#5]
I am getting a debug assertion(debug)/crash(release) build specifically on line 107 TriangleModel.cpp in ClothDemo in TriangleModel::initTriangleConstraint function.

My machine is Windows 8.1 64bit and compiler is VisualStudio2012.

**Comment by janbender** [comment]
Please try to rebuild the project for x64. Another guy reported a similar problem and this solved it.

**Comment by mmmovania** [comment]
yep x64 build solves the problem. I wonder why x86 build does not work?

**Comment by janbender** [comment]
I fixed the x86 problems. Now also the x86 version should work.

**Comment by mmmovania** [comment]
Yes it works fine now. Thanks for the quick resolve.
