### ISSUE TITLE
Compile Error for visual studio 2010

### ISSUE THREAD

**Issue by apapaxiong** [janbender/PositionBasedDynamics#9]
I always meet this error, how to solve this problem ?

positionbaseddynamics-master\extern\eigen\eigen\src\stlsupport\details.h(63): error C2516: 'T' : is not a legal base class
6>          main.cpp(146) : see declaration of 'T'
6>          main.cpp(146) : see reference to class template instantiation 'Eigen::internal::workaround_msvc_stl_support<T>' being compiled
6>          with
6>          [
6>              T=PBD::TetModel *
6>          ]
6>main.cpp(146): error C2819: type 'Eigen::internal::workaround_msvc_stl_support<T>' does not have an overloaded member 'operator ->'
6>          with
6>          [
6>              T=PBD::TetModel *
6>          ]
6>          did you intend to use '.' instead?
6>main.cpp(146): error C2039: 'updateMeshNormals' : is not a member of 'Eigen::internal::workaround_msvc_stl_support<T>'
6>          with
6>          [
6>              T=PBD::TetModel *
6>          ]

**Comment by janbender** [comment]
I cannot reproduce this problem here since I don't have VS2010. Can you give me some more information? Which version of Eigen do you use? Maybe update it.

**Comment by janbender** [comment]
I found a computer with VS2010 and tried to reproduce the problem. It only occurs when I compile PBD for Win32. For x64 it works fine. I will take a closer look at the problem later.

**Comment by janbender** [comment]
I fixed the problem.
